# Generated by Django 3.2 on 2021-05-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_generes_movie_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='movie',
            new_name='movies',
        ),
    ]
